name: affise_project
version: 1.0.0
config-version: 2

profile: clickhouse_profile

# Настройки по умолчанию
models:
  staging:
    +materialized: view
    +schema: staging
    +tags: ["staging"]

  intermediate:
    +materialized: table
    +schema: intermediate
    +tags: ["intermediate"]

  marts:
    +materialized: table
    +schema: marts
    +tags: ["marts"]