affise_project:                # profile name (must match "profile" in dbt_project.yml)
  target: dev                  # active target
  outputs:
    dev:
      type: clickhouse         # ClickHouse driver
      schema: default          # database (in ClickHouse this is the database name)
      host: clickhouse-server  # host (if using docker-compose, this is the service name)
      port: 9000               # native protocol port
      user: default            # ClickHouse user
      password: ""             # password (set if required)
      secure: False            # False = plain connection, True = TLS
      threads: 4               # number of threads for execution